spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eshop?serverTimezone=GMT%2B8
    username: root
    password: root
  flyway:
    baseline-on-migrate: true
  redis:
    port: 6379
    host: localhost
server:
  port: 8082

